# Generated by Django 5.0 on 2024-08-03 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ids',
            field=models.TextField(default='{}'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('dcc1736e-158d-4313-a01e-0699e07bb054'), editable=False, primary_key=True, serialize=False),
        ),
    ]
