# Generated by Django 5.0 on 2024-08-03 13:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_user_ids_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ids',
            new_name='cities',
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f090b9e0-89ee-4b99-84a3-0e99f2ee689d'), editable=False, primary_key=True, serialize=False),
        ),
    ]
