# Generated by Django 5.0 on 2024-08-03 14:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_rename_ids_user_cities_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b98e634f-dfb2-4f18-abc8-aec7536914cd'), editable=False, primary_key=True, serialize=False),
        ),
    ]
