# Generated by Django 5.0 on 2024-08-03 21:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_user_progress_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b0950cdc-52e8-4649-9fbb-e1d99ba9f943'), editable=False, primary_key=True, serialize=False),
        ),
    ]
