# Generated by Django 5.0 on 2024-08-03 22:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_remove_user_cities_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e442ec32-e6a9-494d-ac34-58370e058abb'), editable=False, primary_key=True, serialize=False),
        ),
    ]
