# Generated by Django 5.0 on 2024-08-04 12:51

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 8, 4, 9, 51, 18, 799559)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('352a1184-8891-42af-a95d-f60fc6f751fa'), editable=False, primary_key=True, serialize=False),
        ),
    ]
