# Generated by Django 5.0 on 2024-08-04 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0011_alter_user_date_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='json',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default=uuid.UUID('e04b767b-64fa-4ae5-aeea-1d8963a33d2b'), editable=False, primary_key=True, serialize=False),
        ),
    ]
